from criptografiaAps.AbstractCriptModel import AbstractCriptModel
from criptografiaAps.caesar import Caesar
from criptografiaAps.vigenere import Vigenere
from criptografiaAps.vernam import Vernam
from criptografiaAps.argumentos import argument_manipulator